-- Tabela para armazenar códigos de recuperação de senha
CREATE TABLE IF NOT EXISTS password_reset_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  code TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Índice para buscar por email e código
CREATE INDEX idx_password_reset_codes_email_code ON password_reset_codes(email, code) WHERE used = FALSE;
-- Índice para limpar códigos expirados
CREATE INDEX idx_password_reset_codes_expires_at ON password_reset_codes(expires_at) WHERE used = FALSE;
-- Habilitar RLS
ALTER TABLE password_reset_codes ENABLE ROW LEVEL SECURITY;
-- Política: Apenas service role pode acessar
CREATE POLICY "Service role can manage password reset codes"
ON password_reset_codes
FOR ALL
USING (FALSE);
-- Comentários para documentação
COMMENT ON TABLE password_reset_codes IS 'Armazena códigos de 6 dígitos para recuperação de senha';
COMMENT ON COLUMN password_reset_codes.email IS 'Email do usuário solicitando reset';
COMMENT ON COLUMN password_reset_codes.code IS 'Código de 6 dígitos gerado';
COMMENT ON COLUMN password_reset_codes.expires_at IS 'Data/hora de expiração do código (1 hora após criação)';
COMMENT ON COLUMN password_reset_codes.used IS 'Indica se o código já foi utilizado';
-- Função para limpar códigos expirados (executar via cron)
CREATE OR REPLACE FUNCTION cleanup_expired_reset_codes()
RETURNS void AS $$
BEGIN
  DELETE FROM password_reset_codes
  WHERE expires_at < now() OR (used = TRUE AND created_at < now() - INTERVAL '7 days');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
COMMENT ON FUNCTION cleanup_expired_reset_codes IS 'Remove códigos expirados ou usados há mais de 7 dias';
